image: python:3.8.2

stages:
  - ver
#  - init
#  - tests
  - deploy

ver:
  stage: ver
  script:
    - python --version
    - whoami

#init:
#  stage: init
#  script:
#    - apk add postgresql-dev --no-cache
#    - pip install psycopg2-binary
#    - pip install -r requirements.txt

#run_tests:
#  stage: tests
#  script:
#    - apk add postgresql-dev --no-cache
#    - pip install psycopg2-binary
#    - pip install -r requirements.txt
#    - python tests.py

deploy_staging:
  stage: deploy
  script:
    - git config user.email "a.d.manolache@student.tudelft.nl"
    - git config user.name "amanolache"
    - git remote remove stage
    - git remote add stage https://heroku:$HEROKU_API_KEY@git.heroku.com/nemo-live-science-dev.git
#    - git add .
#    - git commit -m 'deploying to staging server'
    - git push stage master
    - echo "Deployed to Staging Server https://nemo-live-science-dev.herokuapp.com"
  environment:
    name: staging
    url: https://nemo-live-science-dev.herokuapp.com/
  when: manual
#   only:
#     - dev

deploy_production:
  stage: deploy
  script:
    - git config user.email "a.d.manolache@student.tudelft.nl"
    - git config user.name "amanolache"
#    - git remote add pro https://heroku:$HEROKU_API_KEY@git.heroku.com/nemo-live-science.git
    - git push pro master
    - echo "Deployed to Production Server https://nemo-live-science.herokuapp.com"
  environment:
    name: production
    url: https://nemo-live-science.herokuapp.com/
  when: manual
#   only:
#     - master