image: python:3.8.2

stages:
  - ver
  - test
  - deploy

ver:
  stage: ver
  script:
    - python --version
    - whoami

test:
  services:
  - postgres:alpine
  variables:
    POSTGRES_DB: test
    POSTGRES_USER: test
    POSTGRES_PASSWORD: test
  script:
  - export APP_SETTINGS=config.CITestingConfig
  - apt-get update -qy
  - pip3 install -r requirements.txt
  - coverage run --source api --branch -m pytest api
  - coverage report


deploy_staging:
  stage: deploy
  script:
    - git config user.email "a.d.manolache@student.tudelft.nl"
    - git config user.name "amanolache"
    - git checkout dev
    - git remote remove stage
    - git remote add stage https://heroku:$HEROKU_API_KEY@git.heroku.com/nemo-live-science-dev.git
    - git push stage dev:master
    - echo "Deployed to Staging Server https://nemo-live-science-dev.herokuapp.com"
  environment:
    name: staging
    url: https://nemo-live-science-dev.herokuapp.com/
  when: manual
  only:
    - dev

deploy_production:
  stage: deploy
  script:
    - git config user.email "a.d.manolache@student.tudelft.nl"
    - git config user.name "amanolache"
    - git checkout master
    - git remote remove pro
    - git remote add pro https://heroku:$HEROKU_API_KEY@git.heroku.com/nemo-live-science.git
    - git push pro master:master
    - echo "Deployed to Production Server https://nemo-live-science.herokuapp.com"
  environment:
    name: production
    url: https://nemo-live-science.herokuapp.com/
  when: manual
  only:
    - master